# This workflow updates the manifest.yml

name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update_manifest_file:
    name: update manifest file
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4
        
      - name: ğŸ”¢ Adjust version number
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/dynamic_energy_cost/manifest.json"
            
      - name: ğŸ“¦ Created zipped release package
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/dynamic_energy_cost"
          zip dynamic_energy_cost.zip -r ./

      - name: â¬†ï¸ Upload zip to release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: ${{ github.workspace }}/custom_components/dynamic_energy_cost/dynamic_energy_cost.zip
        
